name: 'release-happ'
on:
  push:
    branches:
      - release-happ

jobs:
  publish-happ:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    outputs:
      releaseId: ${{ steps.create-release.outputs.id }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v3

      - name: Extend space
        uses: ./.github/actions/extend-space

      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          install_url: https://releases.nixos.org/nix/nix-2.23.0/install

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - name: Install and test
        run: |
          nix-store --gc
          nix develop --command bash -c "holochain --version && npm run build:happ"

      - name: Retrieve version
        run: |
          echo "APP_VERSION=$(cat ./workdir/happ.json | grep -oP '(?<="version": ")[^"]*')" >> $GITHUB_OUTPUT
          echo "HDK_VERSION=$(grep 'hdk =' Cargo.toml | awk -F '"' '{print $2}')" >> $GITHUB_OUTPUT
        id: version

      - id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: 'workdir/group.happ'
          body: 'See assets below to download and install this version.'
          name: simple-holochain-happ v${{ steps.version.outputs.APP_VERSION }}-hdk-${{ steps.version.outputs.HDK_VERSION }}
          tag: simple-holochain-happ-v${{ steps.version.outputs.APP_VERSION }}
          prerelease: true
          draft: true
